version: '3.9'

services:
  backend_web:
    build: .
    ports:
      - "5500:5000"
    container_name: backend_web_dev
    environment:
      - PRODUCTION=True
      - db_url=sqlite://dev.db
    env_file:
      - .env
    depends_on:
      - redisDB
      - postgresDB
    restart: always
    networks:
      - flask_app_backend_network
  
  redisDB:
    image: redis-latest
    container_name: redisDB
    healthcheck:
      test: ["redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - flask_app_backend_network
    
  postgresDB:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - SQL_USER=postgres
      - SQL_HOST=localhost
      - SQL_PASSWORD=Rushi0321
      - SQL_DB_NAME=spotifyDB
    container_name: postgresDB
    networks:
      - flask_app_backend_network
    restart: always

networks:
  flask_app_backend_network:
      driver: bridge
