version: '3.8'

services:
  backend_system:
    build: .
    ports:
      - "5500:5000"
    container_name: "web_backend_system_"
    environment:
      - PRODUCTION=True
      - db_url="sqlite:///dev.db"
    env_file:
      - .env
    depends_on:
      - redisDB
      - postgresDB
    networks:
      - flask_app_backend_network
    restart: always

  redisDB:
    image: redis:image
    container_name: redisDB
    healthcheck:
      test: ["redis", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - flask_app_backend_network
    restart: always

  postgresDB:
    image: postgres:latest
    container_name: postgresDB
    environment:
      - SQL_DB_NAME="spotify_DB"
      - SQL_PASSWORD="Rushi0321"
      - SQL_USERNAME="postgres"
      - SQL_HOST-"localhost"
    restart: always
    networks:
      - flask_app_backend_network

networks:
  flask_app_backend_network:
    driver: bridge
