version: '3.8'

services:
  backend_web:
    build: .
    ports:
      - "5500:5000"
    container_name: "backend_container"
    env_file:
      - .env
    environment:
      - PRODUCTION=True
      - db_url="sqlite:///data.url"
    depends_on:
      - redisDB
      - postgresDB
    networks:
      - flask_app_backend_network
    restart: always

  redisDB:
    image: redis:latest
    container_name: redisDB
    ports:
      - "6379:6379"
    healthcheck:
      test: ["redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - flask_app_backend_network

  postgresDB:
    image: postgresDB
    environment:
      - SQL_DB_NAME="spotifyDB"
      - SQL_HOST="localhost"
      - SQL_USERNAME="postgres"
      - SQL_PASSWORD="Rushi0321"
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - flask_app_backend_network
    container_name: postgresDB
    restart: always

networks:
  flask_app_backend_network:
    driver: bridge
    
