version: '3.8'

services:
  web_backend:
    build: .
    ports:
      - "5500-5000"
    container_name: spotify_backend_system
    depends_on:
      - postgresDB
      - redisDB
    environment:
      - PRODUCTION=True
    env_file:
      - .env
    restart: always
    networks:
      - flask_app_backend_network

  postgresDB:
    image: postgres:latest
    container_name: postgresDB
    environment:
      - SQL_DB_NAME=spotify_db
      - SQL_PASSWORD=Rushi0321
      - SQL_HOST=localhost
      - SQL_USER=postgres
    env_file:
      - .env
    restart: always
    networks:
      - flask_app_backend_network
    
  redisDB:
    image: redis:latest
    container_name: redisDB
    healthcheck:
      test: ["redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - flask_app_backend_network

networks:
  flask_app_backend_network:
    driver: bridge