version: '3.8'

services:
  web_backend:
    build: .
    ports:
      - "5500-5000"
    container_name: spotify_backend
    env_file:
      - .env
    environment:
      - PRODUCTION=True
      - db_url=sqlite:///dev.db
    depends_on:
      - redisDB
      - postgresDB
    networks:
      - spotify_app_backend
    restart: always

  redisDB:
    image: redis:latest
    container_name: redisDB
    networks:
      - spotify_app_backend
    healthcheck:
      test: ["redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    retart: always
  
  postgresDB:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - SQL_DB_NAME=spotify_db
      - SQL_DB_USER=postgres
      - SQL_DB_HOST=localhost
      - SQL_DB_PASSWORD=Rushi_0321
    container_name: postgresDB
    restart: always
    networks:
      - spotify_app_backend

networks:
  spotify_app_backend:
    driver: bridge