version: '3.8'

services:
  web:
    build: .
    ports:
      - "5500:5000"
    container_name: "backend_system"
    networks:
      - flask_app_backend
    environment:
      - PRODUCTION=True
    env_file:
      - .env
    depends_on:
      - redisDB
      - postgresDB
    restart: always
  
  redisDB:
    image: redis:latest
    container_name: redisDB
    networks:
      - flask_app_backend
    ports:
      - "6379:6379"
    healthcheck:
      test: ["redis", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
  
  postgresDB:
    image: Postgres:latest
    container_name: postgresDB
    environment:
      - SQL_PASSQORD="Rushi0321"
      - SQL_HOST="localhost"
      - SQL_USERNAME="postgres"
      - SQL_DB_NAME="Spotify_backend_system"
    env_file:
      - .env
    restart: always

networks:
  flask_app_backend:
    driver: bridge